version: '3'

services:
  php:
    build: docker/php
    working_dir: /srv/app
    volumes:
      # Comment out the next line in production
      - .:/srv/app
      # PHP conf
      - ./docker/php/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./docker/php/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/usr/local/etc/php/conf.d/php-optimized-for-symfony.ini:/usr/local/etc/php/conf.d/php-optimized-for-symfony.ini:ro # A garder ??
      - ./docker/php/usr/local/etc/php/conf.d/xdebug-phpstorm.ini:/usr/local/etc/php/conf.d/xdebug-phpstorm.ini:ro
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - "8083:9001"
    restart: on-failure
    user: 1000:1000
    networks:
      fil-ariane-client-v1:
        ipv4_address: 100.1.2.2

  nginx:
    build: docker/nginx
    volumes:
      - .:/srv/app
      - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "82:80"
    restart: always
    networks:
      fil-ariane-client-v1:
        ipv4_address: 100.1.2.4
        aliases:
          - fil-ariane-client.local

volumes:
  databases:
  esdata:
    driver: local

networks:
  fil-ariane-client-v1:
    driver: bridge
    ipam:
      config:
        - subnet: 100.1.2.0/24